// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // migrate 請用 Neon Direct（無 -pooler）；App 執行期用 DATABASE_URL（pooled）
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
